---
Name: restful-config
---
Level51\JWTUtils\JWTUtils:
  lifetime_in_days: 365
  renew_threshold_in_minutes: 60

SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Middleware\CanonicalURLMiddleware:
    properties:
      enforceTrailingSlashConfigIgnorePaths:
        - 'api/'